spring:
  datasource:
    username: xxxx
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: xxx
  application:
    name: test-app
  profile:
    active: myprofile
  cloud:
    gcp:
      sql:
        credentials:
          encoded-key: ${GCP_CREDENTIALS_ENCODED_KEY}
        instance-connection-name: xxxx:xxx:xxx
        database-name: xxx
    vault:
      host: localhost
      port: 8200
      scheme: https
      uri: https://localhost:8200
      token: xxxx
      enabled: true
      authentication: TOKEN
      fail-fast: true
      read-timeout: 30000
      connection-timeout: 30000
      ssl:
        trust-store: file:///trustore.jks
        trust-store-password: password
  config:
    import:
      vault://secrets/${spring.application.name}